### ISSUE TITLE
location.hash is changed to #! when selecting an option with mouse

### ISSUE THREAD

**Issue by drm227** [xcash/bootstrap-autocomplete#103]
I am using bootstrap-autocomplete with a <select> element, and retrieving options from a REST service using the searchPost event.  Everything works fine when I use the keyboard to scroll through the options and select one.  But if I use the mouse to select an option, the location.hash value is changed to #! (causing the browser to push an entry onto its history stack).  This breaks the hash-based routing that the single page application is using.

Stepping through the call stack shows that this is happening when in v.handle in jquery.min.js

If there is a workaround, please let me know.

Thanks,
Dennis

**Comment by xcash** [comment]
Check the version you're using. It's an old behavior.

**Comment by drm227** [comment]
Upgrading from 2.3.5 to 2.3.7 made the problem go away.

Thanks,
Dennis
