### ISSUE TITLE
Another json format mapping

### ISSUE THREAD

**Issue by Gitsko** [xcash/bootstrap-autocomplete#104]
Hello, 

I have a JSON file with other structures such as. 
[
    {
        "latitude": 57.092759,
        "longitude": 9.849243,
        "departure": "XXX",
         "destination": "AAA",
         "description": "descriptionA",
        "type": "typeX",
         "state": "inactive"
    },
.....
]

I want to populate a select field with description as text and destination as value.

Is this possible, if yes how ?

**Comment by xcash** [comment]
It is possible and the test page is doing a similar thing.
Just check the documentation / examples.
