### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Annu-anoop-gmail-com** [xcash/bootstrap-autocomplete#12]
Demo page at "https://gitcdn.link/cdn/xcash/bootstrap-autocomplete/1c73df45ff7f6844a833ee96ebd54d1a6bc027f6/dist/latest/index.html" is not working

**Comment by xcash** [comment]
@Annu-anoop-gmail-com that is not a legit demo page. Please follow the Demo link in this repo homepage. :)

**Comment by anentropic** [comment]
it's the page linked from:
https://bootstrap-autocomplete.readthedocs.io/en/latest/

(different hash at the moment, still broken)
https://gitcdn.link/cdn/xcash/bootstrap-autocomplete/866891c6aa9b8e9b89fdf2b055916524f20fa553/dist/latest/index.html

**Comment by xcash** [comment]
@anentropic gotcha thanks. :) Fixed!
