### ISSUE TITLE
How to perform new action

### ISSUE THREAD

**Issue by userbig** [xcash/bootstrap-autocomplete#13]
Hi.
I`m trying to perform new action after when new autocomplete value was founded and selected inside dropdown. Like to open a new page.
I guess I need to customize dropdown template to set href attr to dropdown entrie.

Also, you have typo in doc:

```
formatResult
        callback(item)
             Returns:	
                An object { id: myItemId, text: myfancyText, html**?**: myfancierHtml }.

```

**Comment by xcash** [comment]
Hi @userbig 
You can subscribe on events fired upon selecting the item. [Docs](https://bootstrap-autocomplete.readthedocs.io/en/latest/#events)

```

$('.myAutocompleteField').on('autocomplete.select', function (evt, item) {
  // do stuff. like submitting form, open a page and such
});
```
