### ISSUE TITLE
Cross Domain Option

### ISSUE THREAD

**Issue by LendaUrbana** [xcash/bootstrap-autocomplete#130]
Apis calls in external domains

Need for crossDomain in ajax

I made changes to the code below and it would be a good choice to use. The changes are on lines 91 and 411
[new_code.txt](https://github.com/xcash/bootstrap-autocomplete/files/7091745/new_code.txt)

**Comment by xcash** [comment]
Hi @LendaUrbana 
When using with crossdomain (jsonp) you usually need to add other parameters too.
In these type of scenarios is better to customize the ajax call using the provided events.
