### ISSUE TITLE
Fails with webpack_require when minimized

### ISSUE THREAD

**Issue by StefanHaug** [xcash/bootstrap-autocomplete#14]
Tried using it for a MVC application.

It works great! Excellent product.

But it fails when compiled and minimized because of the webpack issue.

**Comment by xcash** [comment]
@StefanHaug do you have a full error message? And some more info on how to reproduce your environment?

**Comment by StefanHaug** [comment]
1. Create a new basic MVC project in VS.
2. Download repository from xcash/bootstrap-autocomplete on github.
3. Copy bootstrap-autocomplete.js and bootstrap-autocomplete.min.js from the zip-file and include in project.
4. Change the bundle configuration to this:
`			bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
					  "~/Scripts/bootstrap.js",
					  "~/Scripts/bootstrap-autocomplete.js"));`
5. Enable optimization by adding this code:
`BundleTable.EnableOptimizations = true;`

You should get the webpack_require error in browser console.

**Comment by xcash** [comment]
@StefanHaug hmmm I work on Linux, I can't have a VS environment to try this out.
Is the error meaningful in any way or just a generic error?

As blind as I am i can suggest to try using the minified versions.

**Comment by StefanHaug** [comment]
Visual Studio Code is free and runs on linux as well.

The console error is:
`main.ts:1 Uncaught ReferenceError: __webpack_require__ is not defined
    at eval (main.ts:1)
    at Object../src/main.ts (bootstrap?v=kFcN2ieuVvciiZ6_uiNjyXcw_0rHCWe7Cgl8C1b-5701:1)
    at t (bootstrap?v=kFcN2ieuVvciiZ6_uiNjyXcw_0rHCWe7Cgl8C1b-5701:1)
    at bootstrap?v=kFcN2ieuVvciiZ6_uiNjyXcw_0rHCWe7Cgl8C1b-5701:1
    at bootstrap?v=kFcN2ieuVvciiZ6_uiNjyXcw_0rHCWe7Cgl8C1b-5701:1`

I believe the minified version is used when you enable optimizations for bundling.

**Comment by xcash** [comment]
@StefanHaug I use VSCode. I didn't know you could start an MVC boilerplate project from vscode. :D

I really don't know why that error. The minified version is working in the browser... 
I'll try to reproduce the error locally.

**Comment by StefanHaug** [comment]
Did you reproduce the issue?

**Comment by xcash** [comment]
@StefanHaug no. I cannot create a boilerplate MVC project from VSCode.. :/

**Comment by StefanHaug** [comment]
@xcash, ok, I guess I could reference the CDN's directly instead of bundling them. No biggie.

**Comment by justintoth** [comment]
Ran into the same issue today when deploying bootstrap-autocomplete to my prod environment (with bundling / minification.) I implemented the suggested workaround of referencing the bootstrap-autocomplete.js file in a separate script tag instead of in my bundle js, however this really should be fixed so we don't have to do that.

**Comment by xcash** [comment]
Hi @justintoth 
I would love to fix this bu I'm still unable to reproduce the problem.. :(
