### ISSUE TITLE
Add header to search result

### ISSUE THREAD

**Issue by kennethhaspeel** [xcash/bootstrap-autocomplete#16]
I just discovered this yesterday and it works great and is very easy to use (that last bit is perfect for me :-) ).

But i was wondering if it was possible to add a header row to the search result. My results are formatted in rows with 4 columns, which works great with the formatResult option. But i would like to add titles to the columns. In my case, two columns contain dates and i would be nice if i could show what those dates stand for.

Second thing. I select a value from the results. I put focus on the input. If the input loses focus, the autocomplete.select fucntion is executed. The same happens when focus on input and i minimize-maximize the window.  When using Developer Tools, the autocomplete.select fucntion is executed each time i click on something in the Developer Tools section. 
When a vlaue is selected and i put focus on the input, the search is resubmitted

**Comment by xcash** [comment]
Hi @kennethhaspeel and thanks :)

Regarding the header, sorry but i don't see any easy way to add titles cause the results container is a native bootstrap's dropdown. :(

For the select behavior. The componente fires autocomplete.select on change, blur, ENTER. It is indeed strange an event when the selected item remains the same. I'll check this out.

**Comment by kennethhaspeel** [comment]
I was thinking about adding/prepending a disabled dropdown-item : [https://getbootstrap.com/docs/4.3/components/dropdowns/#disabled]
but i'm afraid my javascript just isn't good enough to figure it out. The class "show" is added at a certain time. If, at the same time, a disabled dropdown item could be added, i think it would come close to something like table header.

About the unexpected behavior. I think (but not sure) it's a "feature" of the blur method. When i try the example page [https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_blur_alert], it has the same behavior. Focus on input, minimize, maximize, blur is executed.
But like i said, not an expert in javascript, so not sure

**Comment by xcash** [comment]
@kennethhaspeel sorry for late reply. I can implement a 'disabled' flag if it is still needed. :)

**Comment by xcash** [comment]
@kennethhaspeel Implemented in latest release 2.2.0 :)
