### ISSUE TITLE
How to show suggestions even when focus not on input

### ISSUE THREAD

**Issue by travisbrady** [xcash/bootstrap-autocomplete#17]
I'm making a demo app intended to compare two backend autocomplete algorithms against each other. So I want to type in one, then copy the input prefix to the other and then display the autocomplete dropdown for _both_ at the same time.

But currently when one typeahead box has focus it will show results in the dropdown, but the other box will not unless I click it thereby closing the other dropdown.

Is there some property I can set to always show the dropdown provided the input contains some text?

Example (note dropdown active on left, but not on right):
![image](https://user-images.githubusercontent.com/38363/57743870-7f9ceb00-768c-11e9-8cf8-19cd5d8ced22.png)

**Comment by xcash** [comment]
hmm.. there is no such thing as preventhide. 
But the real problem is that the second autocomplete doesn't show up because one of the first checks it does is "am i focused?"

**Comment by travisbrady** [comment]
got it. thanks for your response
