### ISSUE TITLE
Clicking on an autocomplete result scrolls to top page

### ISSUE THREAD

**Issue by dersleeper** [xcash/bootstrap-autocomplete#18]
How to reproduce:
Search for something. Click (not press tab) on one of the results. The browser jumps to the top of the page. This is probably due to anchor (#) behaviour?

Can be reproduced in Chrome and Firefox.

**Comment by xcash** [comment]
Fixed in later release thanks @dersleeper :)

**Comment by dersleeper** [comment]
Thanks for the quick fix. *thumbsUp*

**Comment by dersleeper** [comment]
Quick question: The bug is marked for the 2.2.0 release. But when I look at the 2.2.0 release the change does not seem to be included.

**Comment by xcash** [comment]
@dersleeper strange. do you still see the issue here:

https://raw.githack.com/xcash/bootstrap-autocomplete/v2.2.0/dist/latest/testdata/test-issue-18.html

**Comment by dersleeper** [comment]
For reference, I downloaded: https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.2.0/dist/latest/bootstrap-autocomplete.min.js

Then I searched for the fix (which basically boiled down to searching for the string "#!") and couldn't find it.

**Comment by xcash** [comment]
I missed the minified version generation in last release :( 
I just release a 2.2.1 version to fix this. 
Thanks a lot @dersleeper let me know if it works!

**Comment by dersleeper** [comment]
Now it works. Thanks again for the quick work!
