### ISSUE TITLE
Autocomplete dropdown with scrollbar disappears within modal

### ISSUE THREAD

**Issue by valepu** [xcash/bootstrap-autocomplete#20]
Hello,
In my project I have changed dropdowns in order to have a limited width and height and then show scrollbars when the content overflows.

When I use the autocomplete (and so a dropdown appears) inside a modal I have an issue when i try to click on the scrollbars inside a modal because the dropdown disappears.

You can see the issue here:

https://raw.githack.com/valepu/bootstrap-autocomplete/master/dist/latest/index4.html

I have changed the dropdown size in order to show scrollbars. When I use the simple autocomplete I can use the scrollbars without any problem, but when i open the modal and try to scroll by clicking on the scrollbars it disappears.

I reckon this is more of a bootstrap issue because the modal steals the focus (as seen here: https://github.com/select2/select2/issues/600 ) but is there some way to solve the issue directly from the autocomplet?

**Comment by xcash** [comment]
Interesting issue. I need to make some experiments.
Have you tried the proposed "enforceFocus" prototype attribute referened in the linked select2 issue?

**Comment by valepu** [comment]
I've tried putting $.noop but it doesn't work unless I also remove the tabindex attribute from the modal. I can't do this because of accessibility. I found other solutions I'm about to test, I'll let you know

**Comment by valepu** [comment]
None of the solutions i found worked. Only removing tabindex="-1" works, but I really can't renounce to accessibility at the moment

**Comment by valepu** [comment]
I have a fix for this, although it hasn't been thoroughly tested. I added a check if you are clicking on the dropdown but not on a element of the dropdown then it will focus back on the input (I added a setTimeout because Firefox won't allow you to focus back on a item when focusing out of it, go figure!)

If you think this fix is ok i'll make a pull request right away (I modified main.ts and dropdown.ts if you want to check), let me know if you want me to remove the style that adds the scrollbar on the test page before the making the request. 
Repo link: https://github.com/valepu/bootstrap-autocomplete
Test page link: https://raw.githack.com/valepu/bootstrap-autocomplete/7adebd2/dist/latest/index4.html

**Comment by xcash** [comment]
Hi @valepu  thanks! yes please send a pull request. 
Btw for the testing page, i prefer a dedicated test page for this issue, like I usually do in dist/testdata/test-issue-xx.html

I'm looking forward to merging your PR. :)

**Comment by valepu** [comment]
Done :)
I've done some testing yesterday and it seems to work fine
Greetings from Italia!

**Comment by xcash** [comment]
Released v2.2.2 
Thank you very much @valepu  :)
