### ISSUE TITLE
autocomplete.freevalue event no longer triggers after autocomplete.select event happened at least once

### ISSUE THREAD

**Issue by dersleeper** [xcash/bootstrap-autocomplete#25]
**Describe the bug**
I wrote 2 event handlers for my autocomplete field using the provided custom events.
The autocomplete.freevalue event handler works as expected. But once I selected a value from the auto complete result list the freevalue event doesn't seem to trigger anymore. 

**To Reproduce**
1. Goto to the examples&demo page https://raw.githack.com/xcash/bootstrap-autocomplete/master/dist/latest/index4.html
2. scroll to the bottom events search field
3. search for "abc" (or any other value) and tab out (or click somewhere out of the input box)
4. the log correctly lists the "freevalue" event. repeat step 3 any number of times. the "freevalue" event always triggers correctly.
5. search for "abc" and select any of the results (for example "Docker")
6. Now if you repeat step 3 again you no longer trigger the "freevalue" event.

**Expected behavior**
The "freevalue" event should instead still trigger as before.

**Desktop (please complete the following information):**
 - Browser Chrome and Firefox

**Comment by xcash** [comment]
Hi @dersleeper 
Nice catch! This is indeed a bug. When you select an item from the dropdown it is not cleared on subsequent queries.

**Comment by onidlo** [comment]
I confirm this issue still exists in version 2.3.0.

**Comment by xcash** [comment]
@dersleeper @onidlo i think this is solved in 2.3.5

**Comment by cweitat** [comment]
This issue still exists in 2.3.5
