### ISSUE TITLE
Conflict with jQuery UI Autocomplete

### ISSUE THREAD

**Issue by cosmosco** [xcash/bootstrap-autocomplete#27]
**Describe the bug**
This issue only occurs when loading/including jQuery UI (https://jqueryui.com/) on the same page as bootstrap-autocomplete.  This likely is due to a conflict between the "autocomplete" function built into jQuery UI and the "Autocomplete" function in bootstrap-autocomplete.  We are testing with jQuery UI v1.12.1 and bootstrap-autocomplete v2.2.1.  When including both on the same page, the browser console displays two messages - one warning, and one error - and the expected "autocomplete" behavior fails for the associated text input.  Here are examples of the two messages displayed in the browser console:

**Warning: jQuery.Deferred exception: Cannot read property 'VERSION' of undefined TypeError: Cannot read property 'VERSION' of undefined**

**Error: Uncaught TypeError: Cannot read property 'VERSION' of undefined**

This issue occurs whether jQuery UI is loaded from a local copy or via remote CDN.

**To Reproduce**
1. Include jQuery and jQuery UI (locally or via CDN)
2. Include bootstrap-autocomplete.min.js
3. Initialize/bind bootstrap-autocomplete to a text input control on the page, e.g. $("#headerSearch").autoComplete({INSERT PARAMETERS});
4. See warning and error messages in browser console (note that autocomplete will not function)

**Expected behavior**
As mentioned, this issue only occurs on pages with both jQuery UI and bootstrap-autocomplete included.  On pages with only bootstrap-autocomplete, no such messages appear in the browser console, and autocomplete behaves as expected when bound to a text input control.

**Screenshots**
<img width="1920" alt="bootstrap-autocomplete Chrome Console Output 06222019" src="https://user-images.githubusercontent.com/52114680/59969566-49ba1480-951e-11e9-8e98-0092658ae7b1.png">

**Environment/Versions**
 - OS: Windows 10 Pro
 - Browser: Google Chrome v75.0.3770.100
 - bootstrap-autocomplete v2.2.1
 - jQuery UI v1.12.1

**Comment by xcash** [comment]
Sorry @cosmosco  but AFAIK Bootstrap and jQuery UI doesn't work well together.

**Comment by cosmosco** [comment]
Hi @xcash ,

Thanks for your reply!  In our experience, jQuery UI and Bootstrap can coexist without issue.  For example, we make use of it for our FullCalendar control (https://fullcalendar.io/), and experience no compatibility problems with BS4.  The good news is that I believe I identified the problem/incompatibility with bootstrap-autocomplete.  There is a line of code in the bootstrap-autocomplete JS that reads:

`var version_string = $.fn.button.Constructor.VERSION;`

This is the line that errors when coupled with jQuery UI.  However, if I "hard-code" the value of the Bootstrap version in that JS, it works perfectly, as in this example:

`var version_string = '4.3.1';`

Perhaps there's another Constructor object that could be referenced to dynamically obtain the Bootstrap version, which wouldn't conflict with jQuery UI?

Thanks again!

**Comment by nws-jstorm** [comment]
A not really better, but working fix for me was to replace the line with this:
`var version_string = ($().modal||$().tab).Constructor.VERSION;`
Tested in Bootstrap 3 and 4

**Comment by xcash** [comment]
Hi guys, I forgot to close this issue as I added a new option to specify Bootstrap version directly.
Implemented in issue #48

**Comment by joeylevy** [comment]
If you don't want to chase down the answer, here is how he implemented it:

Add the 
bootstrapVersion:'4',
or
bootstrapVersion:'3',
line to your initialization script, depending on which bootstrap version you are using. The version number needs to be a string, so put quotes around it.

Partial example:

        resolverSettings: {
            url: '/vendor/search',
            fail: function (e) {
                console.log('error or whatever');
            }
        },
        bootstrapVersion:'4',
