### ISSUE TITLE
npm package...

### ISSUE THREAD

**Issue by fake-fur** [xcash/bootstrap-autocomplete#3]
hi and thanks for this

is there an npm package for this? if not, will there be one ever?

**Comment by xcash** [comment]
Hi @fake-fur and thank you,
I don't know how exactly npm packaging works so I need to study on this.
Apart from that there is nothing against an npm package. :+1:

**Comment by enstyled** [comment]
@xcash you can read the details in this [blog post](https://zellwk.com/blog/publish-to-npm/). It's best if you do it, as the author of the package.

**Comment by xcash** [comment]
Nice! thank you @enstyled ! I will check it! :)

**Comment by xcash** [comment]
Published on NPM :1st_place_medal:
