### ISSUE TITLE
Feature request: add an option to define delay before execute ajax request

### ISSUE THREAD

**Issue by kslimani** [xcash/bootstrap-autocomplete#30]
**Is your feature request related to a problem? Please describe.**
When you type it send a request for each character typed. It cancels the previous request, but the request is handled by server which results in unnecessary load.

**Describe the solution you'd like**
I great feature would have an option to define a delay (in milliseconds ?) before the ajax request is executed after last character typed.

**Comment by xcash** [comment]
Hi @kslimani. Definitely. I'll put this in the roadmap!

**Comment by jakobdo** [comment]
Debounce / throttling may be the way to go. :)

**Comment by DankaVisa** [comment]
It seems the requestThrottling does not work yet, does it?

**Comment by xcash** [comment]
No it will be available in next release sorry.

Il dom 10 nov 2019, 15:59 DankaVisa <notifications@github.com> ha scritto:

**Comment by osthafen** [comment]
Is there already a timeline for the next release with the requestThrottling?
Thanks

**Comment by onidlo** [comment]
I hope it will be available soon, it is already in Documentation (https://bootstrap-autocomplete.readthedocs.io/en/latest/), but does not work yet...

**Comment by xcash** [comment]
Sorry guys, I will release it ASAP. :/

**Comment by xcash** [comment]
Released! :+1:

**Comment by hoangthGitHub** [comment]
It seems the requestThrottling does not work yet, does it?

**Comment by mikacalvo** [comment]
> It seems the requestThrottling does not work yet, does it?

not working in my case neither
