### ISSUE TITLE
this.items.forEach is not a function

### ISSUE THREAD

**Issue by lukedyson** [xcash/bootstrap-autocomplete#31]
Just testing out a basic install, the script gets my results absolutely fine looking at the network requests and results but the results aren't loading in a dropdown. Screenshot below of the JS error message:

<img width="681" alt="Screenshot 2019-07-05 at 16 24 14" src="https://user-images.githubusercontent.com/52576638/60732382-c64aeb00-9f41-11e9-95f0-6508872a4f33.png">

**Comment by xcash** [comment]
Hi @lukedyson 
Can you post the response you're getting? This problem states that results is not a list.

**Comment by lukedyson** [comment]
Attached...

<img width="922" alt="Screenshot 2019-07-05 at 16 46 32" src="https://user-images.githubusercontent.com/52576638/60733341-7883b200-9f44-11e9-8174-8b8bf2dd9526.png">

**Comment by xcash** [comment]
Uhm. it looks good.. how do you initialize the component? Are you using any particular settings or redefining events?

**Comment by lukedyson** [comment]
Literally just this:

```
$('.basicAutoComplete').autoComplete({
    resolverSettings: {
        url: "search.php"
    }
});
```

**Comment by lukedyson** [comment]
If you want to test in my dev area, it's the search box up top:

https://studio.lukedyson.com/

**Comment by xcash** [comment]
I see. I think the problem is that your server is sending the json response as `text/html` instead of `application/json`
jquery automatically parse json only if it finds a correct content-type header.
Could you check this? :)

**Comment by lukedyson** [comment]
My bad, you are 100% right! I thought I was going mad, much appreciated.

**Comment by marsidorowicz** [comment]
Hi, i have similar problem using parcel, can you explain how you fixed to have proper server json response?
