### ISSUE TITLE
Passing URLs values to click through

### ISSUE THREAD

**Issue by lukedyson** [xcash/bootstrap-autocomplete#32]
I see by default the links have !# in their HREF, how do I go about replacing that with the URL passed in the 'value' from my JSON results, for example:

`[
    {"value":"\/clients\/view\/216\/","text":"Studio 338"},
    {"value":"\/clients\/view\/98\/","text":"Studio Juice"}, 
    {"value":"\/clients\/view\/234\/","text":"Studio Moross"}
]`

**Comment by xcash** [comment]
Hi @lukedyson 
You can subscribe to `autoselect.select' and make a JS redirect.
[Here are the docs](https://bootstrap-autocomplete.readthedocs.io/en/latest/#events)
