### ISSUE TITLE
On click on item, val is not accurate

### ISSUE THREAD

**Issue by encrierdigital** [xcash/bootstrap-autocomplete#34]
On a click on item, the change event do not reflect the choice in val()

this code return empty string : $('input[name="city"]').val()
this one $('#city  option:selected').val() return 'undefined'
this one : $('#city').val() return the text that was typed in input.

All goes well when hitting enter key
Any help much appreciated
Best regards

**Comment by xcash** [comment]
Hi @encrierdigital 
If you need the selected item you need to subscribe to the `autoselect.select` event.
More info [here](https://bootstrap-autocomplete.readthedocs.io/en/latest/#events)

**Comment by encrierdigital** [comment]
Hi,
Thank you, sorry for that, I saw that this morning...
