### ISSUE TITLE
Any way to preload some items in dropdown to show before typing

### ISSUE THREAD

**Issue by Alexplose** [xcash/bootstrap-autocomplete#35]
Is there any way to preload some items in the dropdown, and when none of the preloaded items match the user choice he can type and then use autocomplete ?

**Comment by xcash** [comment]
Hi @Alexplose do you mean starting with autocomplete dropdown open and some items?

**Comment by Alexplose** [comment]
Yeah, show the preloaded items on focus, like an autocomplete with a min length to 0.

**Comment by joneldiablo** [comment]
Is any advance here? I want to show the dropdown when user focus on the input with local data, like a  `select>option{N}` when user start to write the list filter the elements

**Comment by joneldiablo** [comment]
I resolved as follows:

`$(selector).on('focus',(e)=>{$(e.target).trugger('keyup')})`

this way the dropdown shows at focus, and minlegth could be 1 I don't know if work with 0 my service don't return anything without search XD

**Comment by xcash** [comment]
@joneldiablo That works if the field contains some data (since the library checks against minLenght).

**Comment by xcash** [comment]
Closed with #53 :+1:
