### ISSUE TITLE
Add event preventDefault at selected item on Enter

### ISSUE THREAD

**Issue by hrydi** [xcash/bootstrap-autocomplete#37]
**I'd like to prevent Submitted Form**
When items show up, and i select it with an Enter. The Form was submitted, i hope this wouldn't be happen in my case.
I need Enter for select the item, but don't submit the form.

i'am sorry for my english.
Terima Kasih

**Comment by DankaVisa** [comment]
Please also ignore the home/end key code.
Btw, the requestThrottling #30 works perfectly. Good job :)

**Comment by xcash** [comment]
@DankaVisa home/end will be ignored in the next incoming version. :)
