### ISSUE TITLE
How do I update the url being queried?

### ISSUE THREAD

**Issue by Sir-SpankalotUK** [xcash/bootstrap-autocomplete#4]
I have a form with two inputs and and I am passing the contents of both to the script, but the JS is not updating the url, (I included the Date.now() for debugging purposes.

```
$(function () {

  $("#contact").on("focusin change paste keyup", function() {
	$('.contactAutoComplete').autoComplete({
		minLength: 0,
		resolverSettings: {
			url: 'client.php',
			extraData: {'company': document.getElementById('company').value + Date.now() }
		}
	});
  });

});
```

Many Thanks

**Comment by xcash** [comment]
@Sir-SpankalotUK  you mean the ajax call is not using `extraData`?
If so you should use a custom resolver like following:

```
// Advanced 1
$('.advancedAutoComplete').autoComplete({
	resolver: 'custom',
	events: {
		search: function (qry, callback) {
			// let's do a custom ajax call
			$.ajax(
				'testdata/test-dict.json',
				{
					data: { 'qry': qry}
				}
			).done(function (res) {
				callback(res.results)
			});
		}
	}
});
```

You can customize the `data` object in the custom ajax call to suit your needs. That function is called every time a search is triggered.

By the way your code seems wrong conceptually as you are re-creating an autocomplete at each keyup. You should instantiate it only once at start.

**Comment by Sir-SpankalotUK** [comment]
**thanks for your help**, javascript is not my strong suit, the thing that was throwing me, was the json layout needs to change in order to prevent the callback throwing an error, so my code wound up as:-

`$('.contactAutoComplete').autoComplete({
	minLength: 1,
	resolver: 'custom',
	events: {
		search: function (qry, callback) {
			$.ajax(
				'client.php',
				{
					data: { 'q': qry, 'company': document.getElementById('company').value }
				}
			).done(function (res) {
				callback(res.results)
			});
		}
	}
});`

Then the data returned must follow the format used in the **test-dict.json** file.

**Comment by banibanc** [comment]
Hi,

thanks for the answer. Al thought I'd like the url to be customized depending on the element. So I'm currently using data-url attribute to access it. I'd like to do something like :

`
$('.basicAutoComplete').autoComplete({
        resolver: 'custom',
        events: {
            search: function (qry, callback) {
                var active = $elem.parent().find('.active').val();
                $.ajax(
                    $elem.data('url') + '?active=' active,
                    {
                        data: { 'qry': qry}
                    }
                ).done(function (res) {
                    callback(res.results)
                });
            }
        }
    });
`

How can I have the reference of the input here ?
