### ISSUE TITLE
Allow dynamic change of url to fetch

### ISSUE THREAD

**Issue by KrazyMax** [xcash/bootstrap-autocomplete#40]
Hi there!

Thank you so much for this module I am using with Django now! I used to use `django-autocomplete-light`, but too heavy to paremeter with a lot of third parties librairies to manage, with a lot of backend involved and yours is just SO simple to use!

I did not find a way to dynamically change the url to query, and I think it could be a good thing to allow users to do so.

My use case: user can select a platform, and then query games but only those related to that platform selected. Thus, I need to change the value of "platform_id" in my query url. To do this, I would like to read this value located in an `<input>` (for instance), and then change the url to query (for instance, it could go from `/search-games?platform_id=13` to `/search-games?platform_id=25`. 

But for now, the ugly thing I do in order to do that is the following:

```html
<!-- in my template -->
<div id="choose-game">
    <select id="id_game" class="basicAutoComplete" data-url="..." data-noresults-text="">
</div>
``` 

```js
var save_select = $("#choose-game").html() // we make a copy of original html code produced by django app
$('#choose-platform').on('change', function () {
    $('.basicAutoComplete').remove() // we delete present basicAutoComplete instance if exists...
    $("#choose-game").html(save_select) // ... we paste save of select...
    $('.basicAutoComplete').autoComplete({ // ... we initiate 
        resolverSettings: {
            extraData: { // here we give the good value for platform_pk, otherwise it would remain unchanged
                'platform_pk': $('input[name=gameStation]:checked').val()
            }
        }
    })
})
```

This is very ugly (even if it is 100% transparent for end user), thus I would like to find a clean way to do the same!

Thanks for reading, and keep up the good work 🔥

**Comment by xcash** [comment]
Hy @KrazyMax  and thanks :)
Since customizing the url and all the query workflow is quite common i preferred to let the user customize the resolver (the query executor) instead of making the default one heavier with a lot of custom options and such.
To achieve your task you should implement your custom resolver in the `search` event:

```
$('.advancedAutoComplete').autoComplete({
  resolver: 'custom',
  events: {
    search: function (qry, callback) {
      // let's do a custom ajax call
      $.ajax(
        'testdata/test-dict.json', {
          data: {
            'qry': qry
          }
        }
      ).done(function (res) {
        callback(res.results)
      });
    }
  }
});
```

It's super simple and you can customize everything.

I hope this is enough for your use case.

Btw if anyone lands on this issue and thinks it would be better to implement an extraData field please leave a comment in this issue to let me know, thanks :)

**Comment by KrazyMax** [comment]
Hi @xcash, and thank you for your quick answer!

It totally works this way, thanks! ✅
Much cleaner regarding the crap I did.

I agree it could be cool/more convenient to have some `extraData` dict the user could fill and that would be evaluated each time the search call is being made.

Anyway, thank you for your help! 😌

**Comment by KrazyMax** [comment]
And sorry I just saw you gave the exact same answer to a privous close issue!

Also, I had to remove the `.results` of `res.results`, I would get a js error if I did not (if you want to correct your answer for future readers).

**Comment by xcash** [comment]
> Also, I had to remove the .results of res.results, I would get a js error if I did not (if you want to correct your answer for future readers).

It's highly dependent on your result object. In mine it was an object with a `results` attribute. :)

**Comment by stefanscheid** [comment]
... came here cause I just wondered why, when  I set
`data-url="/bla/blubb/"`
the resulting request is 
`blubb/q=whateverIamlookingfor`
missing the "bla" part of the path.
What did I miss?

**Comment by xcash** [comment]
Hi @stefanscheid 

It's really strange... could you please create a fiddle on this issue?
Or maybe post the full markup here.

**Comment by stefanscheid** [comment]
<:o) was a classical PEBKAC. path was OK,  just had my eyes on the wrong column in Firefox Network analysis :-D
Finally I messed up the REST method using @Requestattribute instead of @Modelattribute in Spring boot backend ...

**Comment by xcash** [comment]
Haha! Nice you've resolved then. :)
