### ISSUE TITLE
Demo links to localhost

### ISSUE THREAD

**Issue by localjo** [xcash/bootstrap-autocomplete#42]
I'd like to see a demo of this, but the demo links in the readme point to localhost.

**Comment by localjo** [comment]
Update: I found the working demo links in the readme, but the ones that are wrong are the ones on https://bootstrap-autocomplete.readthedocs.io/en/latest/

**Comment by xcash** [comment]
Hi and thanks.
There is a misunderstanding on this. The section of the docs you're referring is for the local Development environment. It states that, when starting the dev environment, the dev server and docs building server are on localhost on those ports. :)
The public demo link is in this section of the docs: https://bootstrap-autocomplete.readthedocs.io/en/latest/#demo-and-examples

Perhaps it should be moved in a more visible location within that document... :/
