### ISSUE TITLE
Trigger search programmatically on paste event

### ISSUE THREAD

**Issue by JHotown** [xcash/bootstrap-autocomplete#43]
Hello, and thanks for the great work on the plug-in.  I'm trying to get autoComplete to trigger on paste.  The following seems to work fine when pasting from the keyboard, but not from a context menu (right click, paste) or "paste" on iphone.  However, the pasted content is always recognized (i.e. alert or console log will show what's pasted via any approach).

```
$('#AutoComplete').on('paste', function() {
        setTimeout(function() {
		var stuff = $('#AutoComplete').val();
		//alert('pasted = ' + stuff);
            	$('#AutoComplete').autoComplete('search', stuff);
	},0);
});
```

Thanks for any insight.

**Comment by xcash** [comment]
Hi @JHotown 
the library intercepts `keyup`. You could try triggering a `keyup`.
I'll try to setup a test case for this though.
