### ISSUE TITLE
Ability to customise the search parameter name

### ISSUE THREAD

**Issue by enstyled** [xcash/bootstrap-autocomplete#45]
**Is your feature request related to a problem? Please describe.**
The documentation states that the parameter used to do the search is `q`, but there does not seem to be a way to configure that. E.g. if you don't have control on the server-side code and it requires another parameter name.

**Describe the solution you'd like**
Add an option to overwrite the parameter name when initialising the component.

**Describe alternatives you've considered**
Changing the backend code.

**Comment by xcash** [comment]
Typical solution here is to customize the resolver:

```js
$('.advancedAutoComplete').autoComplete({
  resolver: 'custom',
  events: {
    search: function (qry, callback) {
      // let's do a custom ajax call
      $.ajax(
        'testdata/test-dict.json', {
          data: {
            'qry': qry
          }
        }
      ).done(function (res) {
        callback(res.results)
      });
    }
  }
});
```

Btw such parameter makes sense for quick customization. I'll keep this as an enhancement! :)

**Comment by xcash** [comment]
Use `queryKey` setting:

```js
$('.basicAutoCompleteQParameter').autoComplete({
  resolverSettings: {
    url: 'testdata/test-list.json',
    queryKey: 'search'
  }
});

```
