### ISSUE TITLE
Version detection not working with customized bootstrap

### ISSUE THREAD

**Issue by toao** [xcash/bootstrap-autocomplete#48]
**Bug**
The bootstrap version detection via ```getBootstrapVersion()``` does not work if the button.js file is not loaded, which can happen for customized (stripped down) bootstrap packages.

**To Reproduce**
1. Create a customized bootstrap package without button.js
2. Bootstrap-autocomplete initialization fails in https://github.com/xcash/bootstrap-autocomplete/blob/v2.3.0/src/main.ts#L122 because ```$.fn.button.Constructor``` is not defined 

**Expected behavior**
Bootstrap version detection should work without assumption of the available components.

**Additional context / Solution idea**
I assume that there's no other way to retrieve the version than to check a specific component for it.

A solution could be to loop through several/all components until one is defined and the version can be accessed. If there's nothing found maybe set a default value.

In addition an option to set/override the bootstrap version when initializing the plugin would be quite handy, then the dynamic detection could be skipped.

**Comment by xcash** [comment]
Hi @toao
An option could be handy.
Btw it's about time to drop support for version 3 in future releases.

**Comment by evan-boissonnot** [comment]
Hi, 
I got the same.
I'm now to maintain old project with custom boostrap ... 
and ... the method getBootstrapVersion fails
