### ISSUE TITLE
how to use with select and selected.

### ISSUE THREAD

**Issue by sant527** [xcash/bootstrap-autocomplete#5]
I have a form with select. I am using Django. I am editing existing values. I want the select with a preselected option. HOw to do this

I have also tried this to set the initial value: But its still blank

        $('.basicAutoComplete').autoComplete(
            {minLength: 1},'set',{'value':1,'text':'sample'}
        );

**Comment by xcash** [comment]
Hi @sant527 you need to do it in two steps. Activate autoselect first and then:

`$('.myAutoSelect').autoComplete('set', { value: myValue, text: myText });`

Try this way and let me know. :)

**Comment by sant527** [comment]
what is activating:

you mean:

```
        $('.basicAutoComplete').autoComplete(
            {minLength: 1}
        );
```

then

`        $('.basicAutoComplete').autoComplete('set', { value: 10, text: "nice" });`
