### ISSUE TITLE
How can I programatically show the drop down?

### ISSUE THREAD

**Issue by fberasategui** [xcash/bootstrap-autocomplete#53]
![image](https://user-images.githubusercontent.com/13060549/77624761-0c593c00-6f21-11ea-9adc-5b766d7c157e.png)

As per the screenshot, I'm trying to show the drop down when the user clicks the right "search" button

**Comment by dipsylala** [comment]
I have a similar use-case. Sometimes the user knows what they want and can type in the start, sometimes they don't and need to 'browse' the options.

**Comment by xcash** [comment]
You must provide an initial item list. 
This is how to customize the resolver to match your use-case.
https://jsfiddle.net/1sa3xcvf/4/

The custom resolver can use the offline list when qry is empty and fetch the list from server when the user types in some values.

@dipsylala  and @fberasategui could you please check if this solution fits your case?
Perhaps I could implement a method to programmatically show dropdown but you still need to provide the initial item list.

**Comment by fberasategui** [comment]
@xcash in my case, I would send the empty query to the server and handle the case server-side (showing first X results, but without filtering, for example)

**Comment by xcash** [comment]
So the trick is the minLength set to 0 and the .trigger() call in the
jsfiddle :) Let me know if it works.

**Comment by xcash** [comment]
Added a method to directly show suggestions
https://bootstrap-autocomplete.readthedocs.io/en/latest/#show-autocomplete
