### ISSUE TITLE
dinamically clear autocomplete 

### ISSUE THREAD

**Issue by dariovinci** [xcash/bootstrap-autocomplete#54]
Hello, after selecting an item from the dropdown i disable the input field and add an X icon on the right that should clear and enable the field. I've tried the following solutions but none of them seem to work 

$('#input').autoComplete('set', { value: null, text: null }); 
$('#input').autoComplete('set', { value: '', text: '' }); 

$('#input').val('');
this one clears the field but  not the value since i can submit the form without errors

Any idea on how to solve it?

**Comment by xcash** [comment]
hmm... seems a buggy test in the 'set' code... 
I'll fix this in next release.

Meanwhile can you try following workaround?

`$(...).val('').trigger('change');`

Let me know if it works.

**Comment by dariovinci** [comment]
The field reset works but the value doesn't reset. I have a form and a select field like this:

`<div class="input-group">
                                <select class="form-control" id="input-patient" name="patient_id" autocomplete="off" required></select>
                                <div class="input-group-append">
                                    <label class="input-group-text" for="input-patient" id="input-patient-icon"><i class="fas fa-user"></i></label>
                                </div>
                            </div>   `

so calling `$(...).val('').trigger('change');`

resets the text field but not the hidden one  therefore if you submit the form you get no errors. I also noticed that selecting an item adds "#!" to the end of the url and using preventDefault on autocomplete.select doesn't fix it.

**Comment by Threetwosevensixseven** [comment]
I've worked around this with: 

```
$('#input').val('').next('input[type=hidden]').val('');
```

for now, but will be watching for the official fix. Thanks!

**Comment by xcash** [comment]
Hi @dariovinci and @Threetwosevensixseven I've just release version 2.3.4 with added support to a 'clear' API command or 'set', null.
Let me know if it works :)
