### ISSUE TITLE
Touch screen bug

### ISSUE THREAD

**Issue by am2222** [xcash/bootstrap-autocomplete#55]
**Describe the bug**
Hello,
I have noticed that by using this library the select does not fire on select event when user clicks on one of the items in the menu. 
**To Reproduce**
1. Go to 'https://raw.githack.com/xcash/bootstrap-autocomplete/master/dist/latest/index.html#!'
2. Enable fire fox's development console and enable responsive view and select iphone. make sure that the `enable touch screen simulation` is on
3. try to work with any of the search boxes. 

**Expected behavior**
when user clicks on an item it should be selected in the menu and its related event fires.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios, windows
 - Browser chrome, safari 

**Smartphone (please complete the following information):**

**Additional context**
the same thing happens on actual ios devices as well. it does not happen to android devices

**Comment by xcash** [comment]
This seems to be an odd Safari bug..... i really don't know how to fix this... 
Anyone?

**Comment by xcash** [comment]
@JackHewson so do you think we might consider this an unsolvable issue? Anyone with a recent ios device can confirm if it is still an issue?
