### ISSUE TITLE
Option to hide drop down when there are no results

### ISSUE THREAD

**Issue by realuser** [xcash/bootstrap-autocomplete#56]
**Is your feature request related to a problem? Please describe.**
Bootstrap 4. I have autocompete on a field such as company name.  The purpose of the field is to show already entered names in case they match but ALSO to allow entering a brand new name.  Assume the name "XYZ" is not in the system, then upon typing "XYZ" the autocomplete shows the drop down with the no results text. 

**Describe the solution you'd like**
I want an option to not show the drop down if there are no results.  For entering a new name the dropdown is unnecessary and confusing.  So as you type, it should show matching values (if there are any), and as you type more if there are no matching values then the dropdown should disappear entirely.

**Describe alternatives you've considered**
I set `noResultsText: ''` but it still shows a blank drop down.

**Additional context**
![image](https://user-images.githubusercontent.com/7472570/79084978-8ba18a80-7ceb-11ea-9a75-60a4b48474d3.png)

**Comment by LouisBellinger** [comment]
Feature much needed ;)
