### ISSUE TITLE
Documentation has a possibly errant question mark

### ISSUE THREAD

**Issue by realuser** [xcash/bootstrap-autocomplete#57]
**Describe the bug**
In the documentation, https://bootstrap-autocomplete.readthedocs.io/en/latest/ under the Configuration Options section the example code shows:

> Returns: | An object { id: myItemId, text: myfancyText, html?: myfancierHtml }.

Is the question mark after the `html` key a typo or intentional? I assumed it was a typo and my code seems to work with out it.

**Screenshots**
![image](https://user-images.githubusercontent.com/7472570/79140997-c815ca80-7d6d-11ea-95d4-f02cd2b1fc14.png)

**Comment by nws-jstorm** [comment]
I think thats intentional to show for documentation purposes that the property is optional.

**Comment by xcash** [comment]
Hi @realuser 
@nws-jstorm  is right. As the library is developed in TypeScript I used the same syntax to represent optional parameters.
In that example the returned object must have `id` and `text` while `html` is used only if defined.
