### ISSUE TITLE
Set custom value doesn´t works

### ISSUE THREAD

**Issue by javierpineros** [xcash/bootstrap-autocomplete#63]
Initially the AutoComplete works fine over select field. But when i try to set custom value throws a exception 

<select class="form-control basicAutoSelect" id="ciiu1" name="ciiu1"
    placeholder="Escriba para buscar..." autocomplete="off"></select>
      
      

**// INITIALLIZATION : WORKS FINE**
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.4/dist/latest/bootstrap-autocomplete.js"></script>
```
<script>
jQuery('#ciiu1').autoComplete({
    	resolverSettings: {
        url: '/ciiu/c.php'
    	},
      minLength: 3,
			autoSelect: true,
			noResultsText: 'no encontrado',
			bootstrapVersion: '4',
			events: {
        searchPost: parseRsp
			}
		});
</script>
```
**-**

**// SET CUSTOM : FAIL**
```
<script>
_value = ciiu1.substring(0,i);
_text = ciiu1.substring(i+1);
jQuery('#ciiu1').autoComplete('set', { value: ciiu1, text: _text });
</script>
```

****

**EXCEPTION IN CONSOLE**
Uncaught TypeError: Cannot read property 'Constructor' of undefined
    at AutoComplete.getBootstrapVersion (main.ts:93)
    at AutoComplete.init (main.ts:152)
    at new AutoComplete (main.ts:68)
    at HTMLInputElement.eval (main.ts:396)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.$.fn.<computed> [as autoComplete] (main.ts:392)
    at HTMLDocument.<anonymous> (userService?task=profileEdit&st=5:692)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)

**Comment by xcash** [comment]
Hi @javierpineros 
are you using a custom build of Bootstrap? 
That error means it fails detecting Bootstrap version.
You can specify the version passing `bootstrapVersion`.
More info here: https://bootstrap-autocomplete.readthedocs.io/en/latest/#bootstrapVersion
