### ISSUE TITLE
how to intialize multiple values when updating a formset in django

### ISSUE THREAD

**Issue by sant527** [xcash/bootstrap-autocomplete#7]
I am using django. I have to edit a value. I have created an update form.

to initialize a single form i do:

`$('.basicAutoComplete').autoComplete('set', { value: 10, text: "nice" });`

But how to do when i have a form with multiple data like  I have a form to update 10 names at a time etc.

**Comment by xcash** [comment]
This is not related to this library but to general jquery. Stackoverflow is a better place to ask this questions.

BTW you can simply use the above line to set each single field according to your values.
