### ISSUE TITLE
Tab triggers autocomplete.freevalue 

### ISSUE THREAD

**Issue by kylesimpson** [xcash/bootstrap-autocomplete#71]
**Describe the bug**
In effort to determine when a user has selected a value from the list and not modified it upon blur, I have relied upon the autocomplete.freevalue event. However, when a user hits "tab" to move to the next field, autocomplete.freevalue is emitted even though a list item is (or should be) still selected.

**To Reproduce**
1. Type value in field that returns results
2. Select a result
3. Hit tab to move to next field index
4. autocomplete.freevalue is emitted

**Expected behavior**
On item 4, autocomplete.freevalue  would not be emitted so long as 'tab' is not interpretted as ascii value in the input.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10
 - Chrome 83

**Comment by kylesimpson** [comment]
The workaround here seems to be just to use a select element in the first place, but the comment remains as unexpected behavior.

**Comment by xcash** [comment]
I need to investigate on this. This could be introduced by a big change I made recently on event triggering..
