### ISSUE TITLE
Marking of machted string disapears with custom formatResult

### ISSUE THREAD

**Issue by daniel-koertvelyessy** [xcash/bootstrap-autocomplete#73]
Hello !

I wanted to enhance the return list by using the code from the example page:

`formatResult: function (item) {
                return {
                    value: item.materialNumber,
                    text: item.materialNumber,
                    html: [item.materialNumber,' - ',
                        item.materialtext
                    ]
                };
            },`

Works nicely,however the search-term is not "marked" on the results, i.e wrapped with a `<b>`. My aim would be to wrap an span with the text-info class. Do I need to do that in the formatResult part or is there an option I have missed?

Thanks and best wishes
Daniel

**Comment by xcash** [comment]
Hi @daniel-koertvelyessy 
When you have custom formatting there is not a simple way to surround the matched word.That could lead to unexpected results.
Therefore in your case you should manage yourself in formatResult. :)

**Comment by daniel-koertvelyessy** [comment]
ok. I solved it now with preg_replace on the php side :D

`$text = preg_replace("/(".$srchterm.")/i", '<b class="text-info">$1</b>', $txtString);`

Cheers!
