### ISSUE TITLE
accessibility: keyup-bound event makes keyboard navigation weird

### ISSUE THREAD

**Issue by stuntsman** [xcash/bootstrap-autocomplete#80]
As the keyboard arrows are handled with a keyup, moving in a larger result list is not possible with long keypress (only with long series of single keypresses). 

It's not only unusual/incomfortable for keyboard freaks, but may easily break accessibility for users with disabilities and/or custom keyboard emulators.

Related code:
https://github.com/xcash/bootstrap-autocomplete/blob/175d1913cf0d2362767b3c2adae8bd2b584d8314/src/main.ts#L238

Comparison with industry standard libraries:

https://jqueryui.com/autocomplete/
https://select2.org/data-sources/ajax

I'd suggest handling all navigation keys (up/down, pgup/pgdn, home/end) with keydown instead to have proper accessibility support.

**Comment by xcash** [comment]
Thanks @stuntsman !
