### ISSUE TITLE
Requires unsafe-eval CSP setting

### ISSUE THREAD

**Issue by Pete-Breen** [xcash/bootstrap-autocomplete#81]
If my site uses the header Content-Security-Policy: script-src 'self', this library doesn't work. It seems the library is using the eval() javascript method and would require me to use 'unsafe-eval' in my CSP setting. Is there a way around this? Can the requirement for using eval() be removed?

**Comment by xcash** [comment]
I don't explicitly use `eval`. But I'm using webpack to modularize the library. 
I'll look into this.

**Comment by xcash** [comment]
Ok I figured it out. This happens when i compile the library in debug mode.
Release versions from 2.3.5 and up will always be compiled in production mode and don't have any eval in it.

**Comment by Pete-Breen** [comment]
Thank you very much
