### ISSUE TITLE
noResultsText: '' only working for first lookup

### ISSUE THREAD

**Issue by klausmeyer** [xcash/bootstrap-autocomplete#83]
**Describe the bug**

I'm using latest version of this library fetched from CDN:
https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@master/dist/latest/bootstrap-autocomplete.min.js
which should currently be commit https://github.com/xcash/bootstrap-autocomplete/commit/175d1913cf0d2362767b3c2adae8bd2b584d8314.

With `noResultsText: ''` as option (see #56) the dropdown isn't shown on no results as expected.
But when I enter something which has results (list is shown) and after that add additional characters to the input field it still shows that empty list.

**To Reproduce**

1. Have some records in the backend like "Doctor John Zoidberg"
2. Enter "John" and wait for the list to show
3. Change "John" to "Johnathan"
4. See the empty box is shown.

**Expected behaviour**

I'd expect to have the same behaviour as when initially searching for something that doesn't exist.

**Screenshots**

![Aug-19-2020 09-25-07](https://user-images.githubusercontent.com/615777/90604976-f7e24c80-e1fd-11ea-9349-69c127527b9e.gif)

**Desktop (please complete the following information):**

Tested in Safari 13.1.2 and Chrome 84.0.4147.125 on MacOS.

**Additional context**

My config:

```js
inputBeneficiaryName.autoComplete({
  minLength: 3,
  resolver: 'custom',
  preventEnter: true,
  noResultsText: '',
  events: {
    search: function (qry, callback) {
      var params = {type: state.receiverType.selected, q: qry};
      $.ajax('/payments/beneficiaries/lookup.json', {data: params}).done(function(r) {
        callback(r.data);
      });
    }
  },
  formatResult: function(json) { return new Beneficiary(json, state.receiverType.selected); },
});
```

Note: `Beneficiary` is just a helper class which provides the needed `id`, `text` and `html` attributes.

**Comment by xcash** [comment]
Hi @klausmeyer  thanks for reporting this issue.
I think it's fixed in master. I'm planning on releasing version 2.3.6 soon to address a bunch of other issues too.

**Comment by klausmeyer** [comment]
Nice thanks 👍. I'll try to grab the master branch version later and see if it is working for me.

**Comment by klausmeyer** [comment]
**Update**: Working fine 🥇

**Comment by danilopolani** [comment]
It still doesn't work for me, maybe because I show the dropdown as soon as the user focus the input. This is my code:

```js
$('#input').autoComplete({
    minLength: 0,
    noResultsText: '',
    resolver: 'custom',
    events: {
      search: (query, cb) => {
        cb(
          items.filter(
            item => item.label.toLowerCase().includes(query.toLowerCase())
          ).slice(0, 5)
        )
      },
    },
    formatResult: (item) => ({
      ...item,
      value: item.label,
      text: item.label,
    })
  })

  // Trigger autocomplete dropdown on click
  $('#input').on('click', function () {
    $('#input').trigger('keyup')
  })
```

The behaviour here is similar: you initially see 5 results when you focus the input; then, when you start searching, if you have no results you still see an empty dropdown (because of an empty `<a></a>` inside it)

**Comment by xcash** [comment]
Hi @danilopolani 
uhm... could you please create a fiddle? Just to ensure it isn't dependent on your result set. (that empty `<a>` is strange...)

**Comment by danilopolani** [comment]
> Hi @danilopolani
> uhm... could you please create a fiddle? Just to ensure it isn't dependent on your result set. (that empty `<a>` is strange...)

Nevermind, I'm an idiot, I was using v2.3.5 and upgrading to v2.3.7 definitely solves it. Sorry again!

**Comment by xcash** [comment]
> Nevermind, I'm an idiot, I was using v2.3.5 and upgrading to v2.3.7 definitely solves it. Sorry again!

Ahah ok no problem! :) :)
