### ISSUE TITLE
Does not work with Angular

### ISSUE THREAD

**Issue by jonghshin** [xcash/bootstrap-autocomplete#88]
**Is your feature request related to a problem? Please describe.**
When selecting a list item, angular does not know that the value is updated.
![capture3](https://user-images.githubusercontent.com/25571245/93271838-d67f6c80-f779-11ea-9b56-10fd3ba64687.gif)
As you can see using Jquery.val() returns the correct value "yahoo" in this case, but the Angular model is still "yah" even after clicking the item "yahoo".

**Describe the solution you'd like**
none.

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by xcash** [comment]
Angular reactive forms are not compatible with this library.
