### ISSUE TITLE
loading icon while working

### ISSUE THREAD

**Issue by shinthawan** [xcash/bootstrap-autocomplete#93]
Hi, is there any way to show a loading gif/icon in the autocomplete field (or next to it), while the resolver is working?

Something like this, ui-autocomplete-loading class appears while jQuery is searching, and hides when the results are shown.
.ui-autocomplete-loading {   
     background: white url("HERE_GOES_LOADING_IMAGE_URL") right center no-repeat;
}

**Comment by xcash** [comment]
Hi @shinthawan 
you can use the event chain to customize your UI.
Like showing a loading icon after the field.

More info on the event chain is here: https://bootstrap-autocomplete.readthedocs.io/en/latest/#search

**Comment by shinthawan** [comment]
Thank you, so I need to implement my own events. One more question, how I should I do the custom request throttling?

**Comment by xcash** [comment]
> Thank you, so I need to implement my own events.

Yes. Maybe in the future I might include something to make it easier.

> One more question, how I should I do the custom request throttling?

Take a look here: https://github.com/xcash/bootstrap-autocomplete/issues/78#issuecomment-668050233

Hope that helps :)
