### ISSUE TITLE
Custom HTML not working

### ISSUE THREAD

**Issue by ArcRanges** [xcash/bootstrap-autocomplete#95]
Hi there,

I can't seem to make the custom HTML work.

HTML
`<input type="text" class="form-control advancedAutoComplete" placeholder="Search..." autocomplete="off">`

jQuery
```
$('.advancedAutoComplete').autoComplete({
  resolver: 'custom',
  events: {
    formatResult: function (item) {
      return {
        value: item.id,
        text: "[" + item.id + "] " + item.text,
        html: [ 
          $('<span>').attr('data-id', item.id), item.text
        ] 
        
      };
    },
    search: function (qry, callback) {
      // let's do a custom ajax call
      $.ajax(
        "{% static 'test-list.json' %}",
      ).done(function (res) {
        callback(res.results)
      });
    }
  }
});
```

What it renders as 
`<a class="dropdown-item" style="overflow: hidden; text-overflow: ellipsis;"My text with no attributes/a>`

I really just want to be able to add a custom data attribute to the dropdown item element but it's not rendering "span" for some reason. I do get the dropdown to show with the right texts though.

Bootstrap version 4

Thanks for your help.

**Comment by xcash** [comment]
Hi @ArcRanges 

Might if be in this line:

`$('<span>').attr('data-id', item.id), item.text`

You're adding an empty `span` **followed** by the `item.text`.
Did you mean putting `text` inside `span`?

Like:

    $('<span>').attr('data-id', item.id).text(item.text)

**Comment by ArcRanges** [comment]
@xcash Hi sorry for the late response. No, it doesn't solve the issue.

Tried `$('<span>').attr('data-id', item.id).text(item.text)` but didn't work.

**Comment by xcash** [comment]
Hi @ArcRanges 
Are you able to reproduce it in a fiddle?
It's nearly impossible to diagnose it without it happening. :)

**Comment by ArcRanges** [comment]
Please check this:

https://jsfiddle.net/09bLygs2/

**Comment by xcash** [comment]
Sorry @ArcRanges  for the delayed reply.
It was easier than expected. I didn't notice initially you put `formatResult` in the `events` object.
It is not an event as it is not async.

Here I moved it up a level and it works. :)

https://jsfiddle.net/jLszh02k/
