### ISSUE TITLE
Can't find latest version as a WebJar in Maven

### ISSUE THREAD

**Issue by cbartolome** [xcash/bootstrap-autocomplete#97]
I've been using the plugin via the WebJar found here:

https://mvnrepository.com/artifact/org.webjars.bowergithub.xcash/bootstrap-autocomplete

The only available version is 2.2.2, though. According to [the WebJars homepage](https://www.webjars.org/), I should be able to find the latest version via its NPM package here:

https://mvnrepository.com/artifact/org.webjars.npm/bootstrap-autocomplete

But that URL leads to a 404. I'm not sure if this is something you initiate on your end or if I should ask the WebJars people for help. Any ideas?

**Comment by xcash** [comment]
Hi @cbartolome 

Well I didn't know the library ended up in maven.... :D So I really don't know how to deal about this issue. I think it's a Maven issue.

Sorry. 

Please let me know if they fix it.

**Comment by cbartolome** [comment]
Okay, I'll see what the WebJars folks say, thanks!

**Comment by cbartolome** [comment]
Looks like all it needed was a few clicks on the "Add a WebJar" button!

**Comment by xcash** [comment]
Great! :)
