### ISSUE TITLE
The selection is not rendering under a <table> td but at the screen's upper left side

### ISSUE THREAD

**Issue by kenfookchoong** [xcash/bootstrap-autocomplete#99]
**Describe the bug**
As what the title says
when you put a textbox with autocomplete function inside a html table td, the div selection will not render under the td but at the screen's most upper left side 

**To Reproduce**
Just put the textbox inside a table's td
  

![image](https://user-images.githubusercontent.com/64672459/102688056-2107fd80-422f-11eb-9411-f8e71befdcec.png)
![image](https://user-images.githubusercontent.com/64672459/102687978-6841be80-422e-11eb-8c87-5334ed3ab8cf.png)

**Expected behavior**
the selection will be at the screen's upper left side

**Comment by kenfookchoong** [comment]
I'm sorry 
after adding the input box inside a div with bootstrap class col then it works ..

<div class="form-row mb-3">
  <label class="col-lg-3">
   TEST
  </label>
  <table>
  
  <tr><td><div class="col-lg-9">
    <input type="search" name="simple_select_text" placeholder="type to search..." autocomplete="off" class="form-control advancedAutoComplete">
  </div></td></tr>
  </table>
</div>

**Comment by gizmotronic** [comment]
I ran into the same thing. An enclosing element needs to include `position: relative`.
